---
apiVersion: v1
kind: Service
metadata:
  name: space-service
  namespace: merlin
  annotations:
    kubernetes.io/elb.id: 0a5e1f0f-a16c-486d-9345-277bd3e83180
    kubernetes.io/elb.class: union
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  ports:
  - name: httpport
    protocol: TCP
    port: 8123
    targetPort: 8123
  selector:
    app: space
  type: LoadBalancer
