resources:
- deployment.yaml
- configmap.yaml
- pvc.yaml
- autoscaler.yaml
namespace: openeuler-signatrust
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: tommylikehu@gmail.com
  kubernetes.ops.os.base: alpine
  kubernetes.ops.owner: husheng
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/signatrust/signatrust-client
  newTag: fe379ceb5815b29b85db147718cc50f3d1837cc5
