apiVersion: apps/v1
kind: Deployment
metadata:
  name: label
  namespace: merlin-icsl
spec:
  selector:
    matchLabels:
      app: label
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'merlin-icsl'
        vault.hashicorp.com/agent-inject-secret-label.yml: 'internal/data/icsl/merlin'
        vault.hashicorp.com/agent-inject-secret-pqsql.crt: 'internal/data/icsl/merlin'
        vault.hashicorp.com/agent-inject-secret-server.crt: 'internal/data/icsl/merlin'
        vault.hashicorp.com/agent-inject-secret-server.key: 'internal/data/icsl/merlin'
        vault.hashicorp.com/agent-inject-secret-kafka.crt: 'internal/data/icsl/merlin'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-perms-label.yml: "0400"
        vault.hashicorp.com/agent-inject-perms-pqsql.crt: "0400"
        vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
        vault.hashicorp.com/agent-inject-perms-server.key: "0400"
        vault.hashicorp.com/agent-inject-perms-kafka.crt: "0400"
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-run-as-group: "1000"
        vault.hashicorp.com/agent-inject-template-label.yml: |  
          {{- with secret "internal/data/icsl/merlin" -}}  
          {{ .Data.data.label }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-pqsql.crt: |  
          {{- with secret "internal/data/icsl/merlin" -}}  
          {{ .Data.data.pqsqlCA }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-server.crt: |  
          {{- with secret "internal/data/icsl/merlin" -}}  
          {{ .Data.data.ServerCrt }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-server.key: |  
          {{- with secret "internal/data/icsl/merlin" -}}  
          {{ .Data.data.ServerKey }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-kafka.crt: |  
          {{- with secret "internal/data/icsl/merlin" -}}  
          {{ .Data.data.kafkaCA }}
          {{- end }}
      labels:
        app: label
    spec:
      tolerations:
      - key: "icsl"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      serviceAccount: merlin-icsl
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/gitea/merlin-label-test:new
        imagePullPolicy: IfNotPresent        
        args:
        - --config-file=/vault/secrets/label.yml
        name: server
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
