resources:
- namespace.yaml
- sa.yaml
- merlin-server
- merlin-website
- merlin-docs
- hook-delivery
- label
- git-access
- space
namespace: merlin-icsl
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
