apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: wangxiyuan
  kubernetes.ops.region: shanghai
kind: Kustomization
namespace: merlin-icsl
resources:
- service.yaml
- deployment.yaml
- pvc.yaml
