---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    failure-domain.beta.kubernetes.io/region: cn-east-3
    failure-domain.beta.kubernetes.io/zone: cn-east-3a
  name: space-data-encrypt-volume
  namespace: merlin-icsl
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-disk
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    failure-domain.beta.kubernetes.io/region: cn-east-3
    failure-domain.beta.kubernetes.io/zone: cn-east-3a
  name: space-log-encrypt-volume
  namespace: merlin-icsl
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-disk
  volumeMode: Filesystem