---
apiVersion: v1
kind: Service
metadata:
  name: space-service
  namespace: merlin-icsl
  annotations:
    kubernetes.io/elb.id: ca0db150-9bec-4da5-9457-ba931a10fe3c
    kubernetes.io/elb.class: union
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  ports:
  - name: httpport
    protocol: TCP
    port: 8123
    targetPort: 8123
  selector:
    app: space
  type: LoadBalancer
