resources:
- ingress.yaml
- service.yaml
- deployment.yaml
- autoscaler.yaml
- tls.yaml
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: muyuying
  kubernetes.ops.region: hk
namespace: qa-robot
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/qa-robot-test
  newTag: 3f78e6aa7b709cc300bc219e987da04a6bb100c5
