---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-repo-deployment
  namespace: gitea-repo-icsl
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gitea-repo-icsl
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'gitea-repo-icsl'
        vault.hashicorp.com/agent-inject-secret-app.ini: 'internal/data/icsl/gitea-repo'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-perms-app.ini: "0700"
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-run-as-group: "1000"
        vault.hashicorp.com/agent-inject-template-app.ini: |  
          {{- with secret "internal/data/icsl/gitea-repo" -}}  
          {{ .Data.data.app }}
          {{- end }}
      labels:
        app: gitea-repo-icsl
    spec:
      tolerations:
      - key: "icsl"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      serviceAccount: gitea-repo-icsl
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: gitea-build
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/gitea/gitea-build:new
        imagePullPolicy: IfNotPresent
        args:
        - --config=/vault/secrets/app.ini
        resources:
          requests:
            cpu: "6"
            memory: 10000Mi
          limits:
            cpu: "6"
            memory: 10000Mi
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3000
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3000
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /var/lib/gitea/
          name: data-volume
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: gitea-repo-data-volume
