---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: gitea-repo-tls
  namespace: gitea-repo-icsl
spec:
  name: gitea-repo-tls
  keysMap:
    ca.crt:
      path: secrets/data/infra-test/domain-tls
      key: tls.cert
    tls.crt:
      path: secrets/data/infra-test/domain-tls
      key: tls.cert
    tls.key:
      path: secrets/data/infra-test/domain-tls
      key: tls.key

