resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- secret.yaml
- pvc.yaml
namespace: majun-anti-poisoning
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/majun/anti-poisoning
  newTag: bd703e716832e9fe3bb2e8150772ce09b104cfab
