apiVersion: v1
kind: Service
metadata:
  name: merlin-docs-service
  namespace: merlin
spec:
  ports:
  - name: https-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: merlin-docs
  type: ClusterIP

  
