resources:
- deployment.yaml
- secrets.yaml
- namespace.yaml
- ingress.yaml
- oauth-proxy.yaml
- cronjob.yaml
commonLabels:
  app: common-jenkins
commonAnnotations:
  email: tommylikehu@gmail.com
  owner: tommylike
namespace: jenkins
images:
- name: swr.cn-north-4.myhuaweicloud.com/openeuler/bak-jenkins
  newTag: fc7cbd36549e0ff0f6f019916a1972ec09c52044
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
